docker-build:
  stage: build
  image: docker:20.10.16-dind   
  tags:
    - rhel8,docker,homenet,lesnet
  services:
    - name: docker:20.10.16-dind
      command: ["dockerd", "--host=tcp://0.0.0.0:2375"]
      alias: 'docker' 
  variables:    
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""  
  before_script:
    - docker context create builder 
    - docker buildx create builder --name multiarch-builder --driver docker-container --use 
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info
  script:    
    - docker buildx build --no-cache --push --platform linux/arm64,linux/arm,linux/amd64 -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .