docker-build:
  # Official docker image.
  image: docker:20.10.16-dind 
  stage: build
  tags:
    - rhel8,docker,homenet,lesnet
  services:
    - docker:20.10.16-dind
  variables:
    #DOCKER_HOST: tcp://gitlab-runner10.lesnet:2375
    #DOCKER_DRIVER: overlay2 
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker buildx build --no-cache --push --platform linux/arm64,linux/arm,linux/amd64 -t "$CI_REGISTRY_IMAGE:latest" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .